help:
	@grep '####' Makefile | grep -v grep | sed -e 's/####//\t\t'

cart: #### Setup Cart Component
	@bash components/cart.sh

catalogue: #### Setup Catalogue Component
	@bash components/catalogue.sh

user: #### Setup user Component
	@bash components/user.sh

shipping: #### Setup shipping Component
	@bash components/shipping.sh
payment: #### Setup payment Component
	@bash components/payment.sh
frontend: #### Setup frontend Component
	@bash components/frontend.sh
mysql: #### Setup mysql Component
	@bash components/mysql.sh
redis: #### Setup redis Component
	@bash components/redis.sh
rabbitmq: #### Setup rabbitmq Component
	@bash components/rabbitmq.sh
mongodb: #### Setup mongodb Component
	@bash components/mongodb.sh

